---
title: "STUDY149: DRAFT Interim Data Analysis"
author: "C2N Diagnostics - proprietary and confidential information. Not to be copied or distributed without C2N written consent."
date: "`r Sys.Date()`"
output:
  html_document:
    theme: default
    toc: true
    toc_float: true
    number_sections: true

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)

now <<- Sys.time()

library(ggplot2)
library(pROC)
library(data.table)
library(caret)
library(plyr)
library(dplyr)
library(ggpubr)
library(expss)
library(ggforce)
library(gridExtra)
# visualizing the effects of variables in a GLM
library(effects)
library(Matrix)
library(readxl)
library(tidyr)
library(stringr)

library(DiagrammeR)
#http://rich-iannone.github.io/DiagrammeR/graphviz_and_mermaid.html
#https://bookdown.org/yihui/rmarkdown-cookbook/diagrams.html

library(usmap)

library(formattable)
#library(tidyr)

library(gridExtra)
library(qwraps2)
options(qwraps2_markup = "markdown")


printpct = function(percentage) {
  if (percentage > 0)
    return(paste0(percentage, "%"))
  else
    return("-")
}

# Plot & visualization
theme_new <- function(base_size = 12, base_family = ""){
  theme_bw(base_size = base_size, base_family = base_family) %+replace%
    theme(
      legend.key=element_rect(colour=NA, fill =NA),
      panel.grid = element_blank(),   
      panel.border = element_rect(fill = NA, colour = "black", size=1),
      panel.background = element_rect(fill = "white", colour = "black"), 
      strip.background = element_rect(fill = NA)
    )
}
theme_set(theme_new(base_size = 16))

categorize_aps = function (APS) {
  
  if (is.na(APS)) {
    return(NA)
  }
  
  if (APS <= 35) {
    return("Low")
  } else if (APS >= 58) {
    return("High")
  } else {
    return("Intermediate")
  }
  
}


study171AbetaData = read_excel("Study171 Abeta Input.xlsx", col_types = c("text", "text", "text", "text", "text", "text", "text", "text", "text", "text", "numeric", "text", "numeric", "numeric", "text", "numeric", "text", "text", "text", "numeric"))
colnames(study171AbetaData)=c("Sample Raw File Name", "Sample Type", "Sample ID", "Sample Name", "Sample Vial Position", "Sample Level", "Sample Acquisition Date", "Compound Name", "Compound Type", "Integration Mode", "Retention Time", "Theoretical Amount", "Calculated Amount", "Peak Area", "ISTD Area", "ISTD Actual Rt", "All Flag Details", "Excluded", "Exclusion Reason", "Dilution Factor")

study171ApoEData = read_excel("Study171 ApoE Input.xlsx", col_types = c("numeric", "numeric", "text", "text", "numeric", "numeric", "numeric", "text", "numeric", "text", "numeric", "text", "numeric", "text", "numeric", "text", "numeric", "text", "numeric", "text", "numeric", "text"))
colnames(study171ApoEData)=c("", "Subject ID", "Proteotype")

study171AgeData = read_excel("Age Data.xlsx", col_types = c("numeric", "text", "text", "numeric"))
colnames(study171AgeData)=c("Subject ID", "col2", "col3", "age")

Abeta_Big_Subset = study171AbetaData[, c('Sample Raw File Name', 'Compound Name', 'Calculated Amount')]
Abeta_Subset = Abeta_Big_Subset[grepl("Abeta_Study171",Abeta_Big_Subset$`Sample Raw File Name`),]

ApoE_Subset = study171ApoEData[, c('Subject ID', 'Proteotype')]

Age_Subset = study171AgeData[, c('Subject ID', 'age')]

Abeta_Wide = spread(Abeta_Subset, 'Compound Name', 'Calculated Amount')

Abeta_Wide[c('sub1', 'sub2', 'sub3', 'Subject ID')] <-str_split_fixed(Abeta_Wide$`Sample Raw File Name`, '_', 4)
Abeta = Abeta_Wide[c('Subject ID', 'Abeta_40', 'Abeta_42')]
colnames(Abeta)=c("Subject ID", "Abeta40_Plasma_IPMS", "Abeta42_Plasma_IPMS")

Mass_Data = merge(x=Abeta, y=ApoE_Subset, by = "Subject ID", all.x = TRUE)

study171data = merge(Mass_Data, Age_Subset, by = "Subject ID")

# Calculate ratio
study171data$Abeta4240_Plasma_IPMS = study171data$Abeta42_Plasma_IPMS/study171data$Abeta40_Plasma_IPMS

# count apoE4 alleles
study171data$apoe4copynr = 0
study171data$apoe4copynr[is.na(study171data$Proteotype)] = NA
study171data$apoe4copynr[study171data$Proteotype == "E2/E4"] = 1
study171data$apoe4copynr[study171data$Proteotype == "E3/E4"] = 1
study171data$apoe4copynr[study171data$Proteotype == "E4/E4"] = 2
# E4 presence
study171data$apoe4present = (study171data$apoe4copynr > 0)

# count apoE2 alleles
study171data$apoe2copynr = 0
study171data$apoe2copynr[is.na(study171data$Proteotype)] = NA
study171data$apoe2copynr[study171data$Proteotype == "E2/E2"] = 2
study171data$apoe2copynr[study171data$Proteotype == "E2/E3"] = 1
study171data$apoe2copynr[study171data$Proteotype == "E2/E4"] = 1
# E2 presence
study171data$apoe2present = (study171data$apoe2copynr > 0)


```



# APS Calculation

Load CLIA model and calculate APS result for all patients

```{r}

# Load the model
model = readRDS("model.clia3_25.rds")


# Calculate the response of the model given the new data
study171data$APS = round(predict(model, newdata = study171data, type='response') * 100)

# Assign category
study171data$APS_Category = sapply(study171data$APS, categorize_aps)


hist(study171data$APS )

```

```{r}
table(study171data$APS_Category)
```

```{r}

table(study171data$Proteotype)

```



# Export

```{r}

exportdata = study171data[c("Subject ID", "age", "Abeta40_Plasma_IPMS", "Abeta42_Plasma_IPMS", "Abeta4240_Plasma_IPMS", "Proteotype", "APS")]

head(exportdata)

write.csv(exportdata, "study171_combined_data.csv")

```
